# -*- coding: utf-8 -*-
"""Punto_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RyLPKr76XsXXICfinr2kBoVhA43Up0iB

##**Punto 2**
"""

def CrearMatriz(matriz_1, matriz_2):                                           # Para que el usuario cree la matriz

  print("Para la primera matriz: ")

  fila=[]
  filas=int(input("Ingrese el número de filas: "))                             # Ingresar el número de filas que quiere
  columnas=int(input("Ingrese el número de columnas: "))                       # Ingresar el número de columnas que quiere
  print("--------------------------------------------")
  for i in range(filas):                                                       # Para ir creando cada fila
    for j in range(columnas):                                                  # Para añadir los valores de la fila (cada columna)
      valor=int(input("Ingrese el valor de la fila " + str(i) + ": "))
      fila.append(valor)                                                       # Se añade el valor a la fila
    matriz_1.append(fila)                                                      # Se añade la fila terminada a la matriz
    fila=[]                                                                    # Se deja vacía la fila para seguir con las demás
  print("--------------------------------------------")

  print("Para la segunda matriz: ")

  fila_2=[]
  filas_2=int(input("Ingrese el número de filas: "))                           # Ingresar el número de filas que quiere
  columnas_2=int(input("Ingrese el número de columnas: "))                     # Ingresar el número de columnas que quiere
  print("--------------------------------------------")
  for i in range(filas_2):                                                     # Para ir creando cada fila
    for j in range(columnas_2):                                                # Para añadir los valores de la fila (cada columna)
      valor_2=int(input("Ingrese el valor de la fila " + str(i) + ": "))
      fila_2.append(valor_2)                                                   # Se añade el valor a la fila
    matriz_2.append(fila_2)                                                    # Se añade la fila terminada a la matriz
    fila_2=[]                                                                  # Se deja vacía la fila para seguir con las demás
  print("--------------------------------------------")
  print("Matriz #1")
  for k in range(len(matriz_1)):                                               # Para imprimir la primera matriz con forma de matriz ;)
    print(matriz_1[k])
  print("--------------------------------------------")
  print("Matriz #2")
  for k in range(len(matriz_2)):                                               # Para imprimir la segunda matriz con forma de matriz ;)
    print(matriz_2[k])

  if columnas!=filas_2:                                                        # Mirar si se puede realizar el producto
    print("Las matrices no cumplen con las condiciones para realizar la operación")
  else:
    Producto(matriz_1, matriz_2, matriz_producto)

def Producto(matriz_1, matriz_2, matriz_producto):
  for i in range(len(matriz_1)):
    fila = []
    for j in range(len(matriz_2[0])):
      fila.append(0)
    matriz_producto.append(fila)

  for i in range(len(matriz_1)):
    for j in range(len(matriz_2[0])):
      for k in range(len(matriz_1[0])):
        matriz_producto[i][j] += matriz_1[i][k] * matriz_2[k][j]

  print("--------------------------------------------")
  print("Matriz producto")
  for m in range(len(matriz_producto)):                                        # Para imprimir la segunda matriz con forma de matriz ;)
    print(matriz_producto[m])

if __name__ == "__main__":
  matriz_1=[]                                                                  # Se crea la matriz vacía
  matriz_2=[]                                                                  # Se crea la matriz vacía
  matriz_producto = []                                                         # El resultado de la operacion
  CrearMatriz(matriz_1, matriz_2)                                              # Se llama la función para crear la matriz