# -*- coding: utf-8 -*-
"""Punto_4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RyLPKr76XsXXICfinr2kBoVhA43Up0iB

##**Punto 4**
"""

def CrearMatriz(matriz):                                                     # Para que el usuario cree la matriz
  fila=[]
  filas=int(input("Ingrese el número de filas: "))                           # Ingresar el número de filas que quiere
  columnas=int(input("Ingrese el número de columnas: "))                     # Ingresar el número de columnas que quiere
  print("--------------------------------------------")
  for i in range(filas):                                                     # Para ir creando cada fila
    for j in range(columnas):                                                # Para añadir los valores de la fila (cada columna)
      valor=int(input("Ingrese el valor de la fila " + str(i) + ": "))
      fila.append(valor)                                                     # Se añade el valor a la fila
    matriz.append(fila)                                                      # Se añade la fila terminada a la matriz
    fila=[]                                                                  # Se deja vacía la fila para seguir con las demás
  print("--------------------------------------------")
  for k in range(len(matriz)):                                               # Para imprimir la matriz con forma de matriz ;)
    print(matriz[k])

def SumaColumna(matriz):                                                     # Para sumar las columnas
  columna=[]
  suma=0
  print("--------------------------------------------")
  for i in range(len(matriz[0])):                                            # Estoy mirando el número de columnas
    for j in matriz:                                                         # Estoy tomando cada fila
      elemento=j[i]                                                          # Estoy tomando el valor de cada fila de la misma columna
      columna.append(elemento)                                               # Añado el elemento de cada columna a la lista de columna
    for k in columna:                                                        # Sumo los elementos de la columna que acabó de identificar
      suma+=k
    print("La suma de la columna " + str(i) + " es: " + str(suma))           # Muestro el resultado de la suma de esa columna
    suma=0
    columna=[]                                                               # Para que no se acumulen los valores de las demás columnas

if __name__ == "__main__":
  matriz=[]                                                                 # Se crea la matriz vacía
  CrearMatriz(matriz)                                                       # Se llama la función para crear la matriz
  SumaColumna(matriz)                                                       # Se llama la función para sumar las columnas