# -*- coding: utf-8 -*-
"""Punto_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RyLPKr76XsXXICfinr2kBoVhA43Up0iB

##**Punto 3**
"""

def CrearMatriz(matriz):                                                      # Para que el usuario cree la matriz
  fila=[]
  filas=int(input("Ingrese el número de filas: "))                            # Ingresar el número de filas que quiere
  columnas=int(input("Ingrese el número de columnas: "))                      # Ingresar el número de columnas que quiere
  print("--------------------------------------------")
  for i in range(filas):                                                      # Para ir creando cada fila
    for j in range(columnas):                                                 # Para añadir los valores de la fila (cada columna)
      valor=int(input("Ingrese el valor de la fila " + str(i) + ": "))
      fila.append(valor)                                                      # Se añade el valor a la fila
    matriz.append(fila)                                                       # Se añade la fila terminada a la matriz
    fila=[]                                                                   # Se deja vacía la fila para seguir con las demás
  print("--------------------------------------------")
  print("Matriz original")
  for k in range(len(matriz)):                                                # Para imprimir la matriz con forma de matriz ;)
    print(matriz[k])

def MatrizTranspuesta(matriz, matriz_transpuesta):                            # Función para crear la matriz transpuesta
    filas = len(matriz)                                                       # Para definir su tamaño según la original
    columnas = len(matriz[0])                                                 # Para definir su tamaño según la original

    for j in range(columnas):                                                 # Empieza tomando las columnas
        fila_transpuesta = []                                                 # La coloqué aquí para que cuando se repita el for no se acumulen valores
        for i in range(filas):                                                # Toma la fila
            fila_transpuesta.append(matriz[i][j])                             # Ubica el elemento en esa ubicación "invertida"
        matriz_transpuesta.append(fila_transpuesta)                           # Se añade la fila que se intercambió

    print("--------------------------------------------")
    print("Matriz transpuesta")
    for k in range(len(matriz_transpuesta)):                                  # Para imprimir la matriz transpuesta con forma de matriz ;)
      print(matriz_transpuesta[k])

if __name__ == "__main__":
  matriz=[]
  matriz_transpuesta=[]                                                       # Se crea la matriz vacía
  CrearMatriz(matriz)                                                         # Se llama la función para crear la matriz
  MatrizTranspuesta(matriz, matriz_transpuesta)                               # Se llama la función para la matriz transpuesta