# -*- coding: utf-8 -*-
"""Punto_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RyLPKr76XsXXICfinr2kBoVhA43Up0iB

##**Punto 1**
"""

def CrearMatriz(matriz_1, matriz_2):                                           # Para que el usuario cree la matriz

  print("Para la primera matriz: ")

  fila=[]
  filas=int(input("Ingrese el número de filas: "))                             # Ingresar el número de filas que quiere
  columnas=int(input("Ingrese el número de columnas: "))                       # Ingresar el número de columnas que quiere
  print("--------------------------------------------")
  for i in range(filas):                                                       # Para ir creando cada fila
    for j in range(columnas):                                                  # Para añadir los valores de la fila (cada columna)
      valor=int(input("Ingrese el valor de la fila " + str(i) + ": "))
      fila.append(valor)                                                       # Se añade el valor a la fila
    matriz_1.append(fila)                                                      # Se añade la fila terminada a la matriz
    fila=[]                                                                    # Se deja vacía la fila para seguir con las demás
  print("--------------------------------------------")

  print("Para la segunda matriz: ")

  fila_2=[]
  filas_2=int(input("Ingrese el número de filas: "))                           # Ingresar el número de filas que quiere
  columnas_2=int(input("Ingrese el número de columnas: "))                     # Ingresar el número de columnas que quiere
  print("--------------------------------------------")
  for i in range(filas_2):                                                     # Para ir creando cada fila
    for j in range(columnas_2):                                                # Para añadir los valores de la fila (cada columna)
      valor_2=int(input("Ingrese el valor de la fila " + str(i) + ": "))
      fila_2.append(valor_2)                                                   # Se añade el valor a la fila
    matriz_2.append(fila_2)                                                    # Se añade la fila terminada a la matriz
    fila_2=[]                                                                  # Se deja vacía la fila para seguir con las demás
  print("--------------------------------------------")
  print("Matriz #1")
  for k in range(len(matriz_1)):                                               # Para imprimir la primera matriz con forma de matriz ;)
    print(matriz_1[k])
  print("--------------------------------------------")
  print("Matriz #2")
  for k in range(len(matriz_2)):                                               # Para imprimir la segunda matriz con forma de matriz ;)
    print(matriz_2[k])

  if filas!=filas_2 and columnas!=columnas_2:                                  # Mirar si se pueden sumar o restar
    print("Las matrices no cumplen con las condiciones para realizar la operación")
  else:                                                                        # La opración que quiera hacer el usuario
    operacion=str(input("Ingrese 'sumar' si desea sumar las matrices o 'restar' si desea restar las matrices: "))
    if operacion=="sumar":                                                        # Para llamar la función suma
     Suma(matriz_1, matriz_2, resultado_matriz)
    elif operacion=="restar":                                                     # Para llamar la función suma
     Resta(matriz_1, matriz_2, resultado_matriz)

def Suma(matriz_1, matriz_2, resultado_matriz):                                # Se crea la función de la suma
  fila_sumada=[]                                                               # Para ir añadiendo las nuevas filas con los resultados sumados
  for i in range(len(matriz_1)):                                               # Para que vaya tomando cada fila
    fila_sumada = []                                                           # Para que no se acumulen los valores que se van sumando de las nuevas filas
    for j in range(len(matriz_1[0])):                                          # Para tomar la posición cada elemento
      suma = matriz_1[i][j] + matriz_2[i][j]                                   # Para tomar los números de las mismas coordenadas en cada matriz y sumarlas
      fila_sumada.append(suma)                                                 # Añadir la suma a la nueva fila de la matriz sumada
    resultado_matriz.append(fila_sumada)                                       # Añadir la fila terminada a la matriz resultante
  print("--------------------------------------------")
  print("Resultado de la suma de las matrices")
  for k in range(len(resultado_matriz)):                                       # Para imprimir la primera matriz con forma de matriz ;)
    print(resultado_matriz[k])

def Resta(matriz_1, matriz_2, resultadi_matriz):                               # Se crea la función de la resta
  fila_restada=[]                                                              # Para ir añadiendo las nuevas filas con los resultados restados
  for i in range(len(matriz_1)):                                               # Para que vaya tomando cada fila
    fila_restada = []                                                          # Para que no se acumulen los valores que se van restando de las nuevas filas
    for j in range(len(matriz_1[0])):                                          # Para tomar la posición cada elemento
      resta = matriz_1[i][j] - matriz_2[i][j]                                  # Para tomar los números de las mismas coordenadas en cada matriz y restarla
      fila_restada.append(resta)                                               # Añadir la resta a la nueva fila de la matriz restada
    resultado_matriz.append(fila_restada)                                      # Añadir la fila terminada a la matriz resultante

  print("--------------------------------------------")
  print("Resultado de la resta de las matrices")
  for k in range(len(resultado_matriz)):                                       # Para imprimir la primera matriz con forma de matriz ;)
    print(resultado_matriz[k])

if __name__ == "__main__":
  matriz_1=[]                                                                  # Se crea la matriz vacía
  matriz_2=[]                                                                  # Se crea la matriz vacía
  resultado_matriz=[]                                                          # El resultado de la operacion
  CrearMatriz(matriz_1, matriz_2)                                              # Se llama la función para crear la matriz1